export const greetings = [
	"We've been waiting for this moment",
	"You're right on time, as always",
	'The guest of honor has arrived',
	"We wondered when you'd show up",
	'Glad you finally made it here',
	'Your presence has been long awaited',
	'Look who decided to walk in',
	'We saved a spot just for you',
	'Your seat has been kept warm',
	"We thought you'd never get here",
	"You're the one we've been watching",
	'Just the person we wanted to see',
	'You were on our minds all day',
	'The time has come at last',
	"We had a feeling you'd appear",
	"Right where you're supposed to be",
	'Your arrival has not gone unnoticed',
	"We've been holding our breath for you",
	"Something told us you'd be here",
	'We kept your place in line',
	'Your name has come up before',
	"We've heard so much about you",
	"Your timing couldn't be more perfect",
	'We almost gave up on you',
	'The whole room was waiting silently',
	"Step inside — we've prepared for you",
	'Every eye was watching the door',
	"You've been on our list awhile",
	"We had a feeling you'd come",
	"We've arranged everything just for you",
	'We set a place at the table',
	"The others said you wouldn't show",
	'Funny — we just mentioned your name',
	"We've been ready since early morning",
	"You're not as late as anticipated",
	"Please, come in — we're all ready",
	"We had a hunch you'd arrive",
	'The door was left open intentionally',
	'We knew this day would come',
	"Ah, the moment we've all anticipated"
];
