services:
  db:
    image: postgres:17.6
    env_file:
      - .env.production
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    restart: always

volumes:
  db_data:
